### ISSUE TITLE
importing `style.scss` into components result in memory leak

### ISSUE THREAD

**Issue by nort3x** [nuxt-modules/tailwindcss#745] opened 2023-10-29 11:48 UTC
### Version
@nuxtjs/tailwindcss: 6.8.0
nuxt: 3.7.4

### Reproduction Link
attached to this issue
[reduced-reproduce.zip](https://github.com/nuxt-modules/tailwindcss/files/13197953/reduced-reproduce.zip)
duce

there is a single `page` in this app which has a single `component`  
it's called `KButton` and it requires to import `style/global.scss` for some reason

see: `componenets/k/Button.vue`

to test this for yourself:
* run `npm run dev`
* run `python3 crash-it.py`

around `500` updates node process will exceed `2G` ram and will crash

leak can be prevented by not importing `style/global.scc` inside the component but why? (see line 52 in `KButton`)

**Comment by ineshbose** [comment] 2023-10-29 12:08
Hi, thanks for opening an issue on this repo.

A few things I'm noting -
1. Your project uses SASS, which is fine - not a problem - but Tailwind prefers and works best with PostCSS.
2. So your `cssPath` is `~/style/global.scss`, but your `nuxt.options.css` also includes `@/style/global.scss` - this module will add the cssPath to `nuxt.options.css` for you, so you don't need to add it there.
3. You also have the file imported in the component - the Tailwind utilties should already be picked up by content configuration and added to your CSS; looking at your config, it seems okay, but you wouldn't need to add anything to content because the module already adds in the appropriate values.
4. Memory leaks usually tend to be on framework scope and this module does so little to create potential for a leak here (though I'm more than open to investigate), so be sure to confirm that there's no related issue on https://github.com/nuxt/nuxt/issues?q=is%3Aissue+memory+leak

**Comment by nort3x** [comment] 2023-10-29 12:49
thanks for the advice, i'm just a beginner and i know this repo has many flaws
i also have to mention that `global.scss` is imported because the component needs other classes (which are themselves imported from else where) and acts as a export gate for my styles 

and i scavenged this minimal reproducible example from my project so sorry if parts of it doesn't make sense 😄 

i've noticed by just replacing tailwind official integration with this module the leak is avoided and old-space gets cleaned after each GC - plus a huge speed gain!

i've been discussing this problem in nuxt community (discord) for a while and after i proposed this they advised me to create the issue here


[avoided.zip](https://github.com/nuxt-modules/tailwindcss/files/13198077/avoided.zip)

**Comment by ineshbose** [comment] 2023-11-19 16:57
I'm closing this. Please feel free to continue discussion over Discord.

**Closed by ineshbose** 2023-11-19 16:57 UTC
Labels: pending

**Comment by nort3x** [comment] 2023-11-19 17:06
why you are closing this?
this didn't receive a proper triage, i added a reproduction example and this is an important issue for this library, i added tailwind directly into my project and it's 10x faster and no leaking - my responsibility toward community is to bringing these up as i see them, I'm not a maintainer of this project but covering it under a carpet is counter intuitive,

cheers 🥂

**Comment by ineshbose** [comment] 2023-11-19 17:15
> my responsibility toward community is to bringing these up as i see them, I'm not a maintainer of this project but covering it under a carpet is counter intuitive,

I appreciate that, and value these issues being opened on this repo. They're helpful in providing a trail to other developers who may hit the same issue, so I'm definitely not looking to cover it under the carpet. 🙂

As we discussed about this issue, there's separate configurations we need to do to work best with this module, while vanilla Tailwind has a different setup. We saw global.scss being a point of regression here, so when we move out styles appropriately, the module should work as intended. I'll be sure to reopen this issue if we get more reports of memory leak, but for now I trust that devs have had appropriate usage of the module and their CSS. 😄
