### ISSUE TITLE
tailwind viewer doesn't work with nuxt 2 and module 5.3.0

### ISSUE THREAD

**Issue by existe-deja** [nuxt-modules/tailwindcss#510] opened 2022-07-20 14:40 UTC
### Version
@nuxtjs/tailwindcss:5.3.0
nuxt: 2.15.8

### Reproduction Link
Go to [https://codesandbox.io/s/optimistic-tree-60k42j?file=/package.json](https://codesandbox.io/s/optimistic-tree-60k42j?file=/package.json)

### Steps to reproduce
open the `/_tailwind` url

### What is Expected?
To get the tailwind config viewer.

### What is actually happening?
I get an error.

**Comment by bmulholland** [comment] 2022-08-17 11:24
This is probably a dupe of https://github.com/nuxt-community/tailwindcss-module/issues/507

The crash is now fixed, as of 5.3.2 / #517, but the viewer still isn't loading for me (nuxt bridge, custom .js tailwind config)

**Comment by ineshbose** [comment] 2023-05-11 10:16
Hi, is this still an issue with v6 (except for `ssr: false` #561)? If so, please do comment and I'll reopen this issue.

**Closed by ineshbose** 2023-05-11 10:16 UTC
Labels: bug
