### ISSUE TITLE
Error with the new nuxt@3.4.2

### ISSUE THREAD

**Issue by maximepvrt** [nuxt-modules/tailwindcss#663] opened 2023-04-21 09:26 UTC
This error `Cannot find module 'postcss-custom-properties'` after update my simple projet with only this dependency form 3.4.1 to 3.4.2

**Comment by ineshbose** [comment] 2023-04-21 10:04
What version of the module are you on? Did you refresh your lock-file? Would help to get a reproduction if possible!

**Comment by alfredomtzrmz** [comment] 2023-04-21 13:52
Same here, using:
```json
{
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.6.6",
    "nuxt": "^3.4.2",
    "typescript": "^4.9.4"
  }
}
```
got this error:
<img width="1473" alt="CleanShot 2023-04-21 at 07 52 41@2x" src="https://user-images.githubusercontent.com/23019968/233653762-74744006-c3a0-4449-84c3-145ac94e455f.png">

**Comment by giticon** [comment] 2023-04-21 20:31
Same error. I deleted the yarn-lock file, reinstalled node_module and the problem was solved.

**Comment by alfredomtzrmz** [comment] 2023-04-21 21:35
> Same error. I deleted the yarn-lock file, reinstalled node_module and the problem was solved.

@giticon  You're right, now works :D

**Comment by ineshbose** [comment] 2023-04-21 23:02
@maximepvrt please confirm, at your convenience, that the above solution (refreshing lock-file) works for you and close the issue if you're happy 😊

**Closed** 2023-04-24 09:41 UTC
Labels: bug
