### ISSUE TITLE
Add "file:" style support

### ISSUE THREAD

**Issue by douglas-bash** [nuxt-modules/tailwindcss#816] opened 2024-02-26 14:55 UTC
On TailwindCss oficial doc, is possible to style a input file, like this example:

[Oficial Doc with example](https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons)

But with TailwindCss for Nuxt, that way to style isn't working. Like the image below:

![image](https://github.com/nuxt-modules/tailwindcss/assets/151532371/c0cc3dec-5ec2-461d-9c5b-c163de4f46eb)

There is a date to release a version to implement this way to style? I really need to use it. If am I doing something wrong, please let me know. To simulate that I just copy the code that is provided at the doc I mentioned lately.

Thank you for your time!

**Comment by kenny-marcante** [comment] 2024-02-26 18:02
same for me here

**Comment by Rafael-Access** [comment] 2024-02-26 18:07
me to

**Comment by ineshbose** [comment] 2024-02-28 08:27
Seems to be working fine with the same snippet from the docs on Nuxt. Can you share a reproduction please?

Feel free to use the module playground - https://stackblitz.com/github/nuxt-modules/tailwindcss/?file=playground%2Fapp.vue

**Comment by ineshbose** [comment] 2024-03-13 10:32
Closing for now. Will open when a reproduction is provided.

**Closed by ineshbose** 2024-03-13 10:32 UTC
Labels: need-repro, pending
