### ISSUE TITLE
loadAndTransform warmup errors with environment CONSOLA_LEVEL=4 

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-modules/tailwindcss#726] opened 2023-09-29 08:53 UTC
### Version
@nuxtjs/tailwindcss: 6.8.0
nuxt: 3.7.4

### Reproduction Link
I'm sorry it's not minimal but it's in my package here for now, I wanted to raise the report first quickly if that's OK and can whittle it down after. https://github.com/components-web-app/cwa-nuxt-module

### Steps to reproduce
run `pnpm dev`

During startup I get lots of errors now like this:
```
 Warmup for /App.js failed with: Failed to load url /App.js (resolved id: /App.js) in /PATH/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /App.ts failed with: Failed to load url /App.ts (resolved id: /App.ts) in /PATH/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
```

It is seemingly trying to warmup files within a another layer.

You'll see I have a tailwind implementation for my module (with a prefix) and then the playground which is using tailwind as usual. This is because the module will be creating its own CSS with a prefix and allow the playground (or final application) to use whatever css framework they choose.

### What is Expected?
No warmup errors

### What is actually happening?
Lots of warmup errors. I think it's related to this package as it all seems to originate from the tailwind.css - please forgive me if I'm wrong, but any guidance into the right direction would be appreciated. Everything works fine in the project but it's just annoying error messages. The full list of warmup errors on every start is:

```
[1] ⚙ Warmup for /App.js failed with: Failed to load url /App.js (resolved id: /App.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /App.ts failed with: Failed to load url /App.ts (resolved id: /App.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /app.js failed with: Failed to load url /app.js (resolved id: /app.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /app.ts failed with: Failed to load url /app.ts (resolved id: /app.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /Error.js failed with: Failed to load url /Error.js (resolved id: /Error.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /Error.ts failed with: Failed to load url /Error.ts (resolved id: /Error.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /error.js failed with: Failed to load url /error.js (resolved id: /error.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /error.ts failed with: Failed to load url /error.ts (resolved id: /error.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /Error.vue failed with: Failed to load url /Error.vue (resolved id: /Error.vue) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /error.vue failed with: Failed to load url /error.vue (resolved id: /error.vue) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /app.config.js failed with: Failed to load url /app.config.js (resolved id: /app.config.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /app.config.ts failed with: Failed to load url /app.config.ts (resolved id: /app.config.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/App.ts failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/App.ts (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/App.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/App.js failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/App.js (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/App.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.js failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.js (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/app.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.ts failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.ts (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/app.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/App.vue failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/App.vue (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/App.vue) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.vue failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.vue (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/app.vue) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/Error.js failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/Error.js (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/Error.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/Error.ts failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/Error.ts (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/Error.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/error.js failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/error.js (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/error.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/error.ts failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/error.ts (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/error.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/Error.vue failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/Error.vue (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/Error.vue) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/error.vue failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/error.vue (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/error.vue) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.config.js failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.config.js (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/app.config.js) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
[1] ⚙ Warmup for /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.config.ts failed with: Failed to load url /@fs/[PATH]/cwa-nuxt-3-module/src/layer/app.config.ts (resolved id: /[PATH]/cwa-nuxt-3-module/src/layer/app.config.ts) in /[PATH]/cwa-nuxt-3-module/playground/assets/css/tailwind.css. Does the file exist?
[1] 
[1]   at loadAndTransform (node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1_sass@1.68.0/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
```

**Comment by danielroe** [comment] 2023-10-11 12:24
These paths are being passed to tailwindcss like this:

https://github.com/nuxt-modules/tailwindcss/blob/main/src/resolvers.ts#L25-L55

When vite is warming up tailwindcss, it seems that tailwind tries to resolve all these paths. This is not coming directly from Nuxt (or indeed the tailwindcss module).

**Comment by ineshbose** [comment] 2023-10-11 12:50
Hi, sorry I haven't been able to look into this in a while.

I'm currently looking for the Tailwind usage in your codebase. The path resolving linked above is for Tailwind JIT/Content configuration, but as you pointed out earlier as well, the module is creating its own CSS and the early errors point to `tailwind.css` file. The relevant part for that is - https://github.com/nuxt-modules/tailwindcss/blob/8ec24ca0b2f0ad6ad55e4facf67fe37232f97f31/src/module.ts#L94-L110

May I ask if you were able to progress in reproducing this with a smaller codebase and/or over Stackblitz? It would also be super helpful if you could point me to a suspected relevant part of your repo where this module is being used or handled.

**Comment by silverbackdan** [comment] 2023-10-11 14:52
Hi both, thank you so much for your time and looking into this. And I'm sorry I have not been more knowledgable in the workings of the packages to try and find the cause. These replies have already been a huge help so I can do a little more digging.

In relation to a more minimal reproduction, I'm afraid I haven't been able to produce this yet, and I'm fully aware it can be a huge sticking point to having issues resolved which I appreciate.

The best way to reproduce right now is this branch:
https://github.com/components-web-app/cwa-nuxt-module/tree/feat/manager-tabs

Simply running `pnpm dev` which will build the playground directory.

With the information provided above, it give me a much clearer understand as to where the code is creating this references to load and allows me to try and do some work on it too. I'm going to try to bring this module in locally and link it into my project so hopefully I can try to trace this a little easier myself as well.

**Comment by silverbackdan** [comment] 2023-10-11 14:59
In the code highlighted by Daniel, I can see through adding some logging that 2 layers are attempting to be scanned, which seems probably reasonable to try and scan each layer.. just in case I suppose?
```
[1] /src/layer
[1] /playground
```

In
https://github.com/nuxt-modules/tailwindcss/blob/main/src/resolvers.ts#L25-L55

And then because files are not existing at all in some/all layers, I think we are getting the warmup errors, but I feel like I'm starting to make progress with the information provided and can see how the code behaves when running in your playground vs my app to see what the differences are.

**Comment by silverbackdan** [comment] 2023-10-11 15:04
What I don't really understand right now, is that in your playground, it is clear all the possibly available files do not exist either. However, running the build on your module does not seem to trigger all the cache warmup errors.

**Comment by silverbackdan** [comment] 2023-10-11 15:16
The CSS file is resolving correctly and the contents of the CSS is simple - even if I use the default CSS the errors are happening. But my tailwindcss is:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I'll update again if I can make head or tails of this issue. Thanks for your input today. I'm not sure how to make a minimal reproduction right now. It's very unclear why it is happening my my module but not your playground right now..

**Comment by silverbackdan** [comment] 2023-10-11 15:39
The strange this is, in my project I seem to be able to remove the layer and my module, so it just ends up as the playground, and the error occurs.

The config returned for both the playground in your module, and within my module seems fine - they both give the file path globs. And if I remove this part of your module not to add any new tailwind content paths, the cache warm error doesn't happen - so it is related somehow.

In my tailwind config, I do extend the content array, however it doesn't seem to make any difference whether I have a config file with any content, or even remove the config file within my playground dir.

I have a feeling the issue may be further down the list of dependencies, because as far as I can see, the content file list produced is the same in this module, and my module...

Very odd.

**Comment by silverbackdan** [comment] 2023-10-13 12:03
I'm trying to whittle down the issue - so far I've removed my entire module and layer from being loaded into the playground application and the issue is still occurring.

https://github.com/components-web-app/cwa-nuxt-module/tree/bug/loadAndTransform

**Comment by silverbackdan** [comment] 2023-10-13 12:13
The above branch is as minimal reproduction as I can provide I *think* - I can't really work out what is triggering the errors. But it's literally just the playground running now with this module

Running `pnpm dev` will show up all the warmup errors.

https://github.com/components-web-app/cwa-nuxt-module/tree/bug/loadAndTransform

**Comment by ineshbose** [comment] 2023-10-13 13:27
Thanks! I'm able to reproduce now on Stackblitz (but using `pnpm dev:http` instead). Trying to investigate....

**Comment by ineshbose** [comment] 2023-10-14 15:59
A couple of notes:
1. Would be great if you add an `index.vue` in `playground/pages/` dir.
2. `tailwind.config.ts` is a TypeScript file - I'd highly encourage you use `export default` instead of `module.exports`.
3. If needed to suppress this error, you could use [content as a function](https://tailwindcss.nuxtjs.org/tailwind/config#merging-strategy) and do `...contentDefaults.slice(0, 6)`, but it's not good to do that - I'll agree.

Now, this is the code from the framework that is not happy:
https://github.com/nuxt/nuxt/blob/1d43cdc908d62411e919cd1b42fa547c8aad0470/packages/vite/src/utils/warmup.ts#L17

The entry point (in `entries: string[]`) to `warmupViteServer` is valid, and then in `deps`, you have the specific files /error.vue, /app.vue, /app.config.ts, etc; first, I am not sure if and how this is being picked from content configuration of this module (over there the absolute paths are valid too); these `deps` seem to come from url `assets/css/tailwind.css` (which may be after tailwind has loaded, ref https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/cacheInvalidation.js#L36). But then, since `warmup` is being called again with those paths, somehow it is looking for those files in `assets/css/tailwind.css` (which is a file, not a dir). Main thing is.. why is this issue happening with your project I wonder? I'm unable to point to what your code/config may be doing to cause this (or even the module code)... Continuing investigation

**Comment by silverbackdan** [comment] 2023-10-15 07:43
Hi @ineshbose 
I can certainly get onto these changes. In my real module, all the pages are configured automatically, so adding an index.vue would end up breaking that module by not loading in the default page loader for every route. The idea with my module is to add pages manually which are not going to be using the API/Page loader defaults. However I can see that for testing this issue, an index.vue could be very useful.

For the other issues - absolutely, that is definitely something I will fix for the ts file - good catch.

For now I will have a wait for the `content as a function` fix as if another fix comes in, it'd cause other issues - but I really appreciate that there is a workaround to suppress these warnings on build.

And indeed - I wonder if I should start building a module from the ground up again, using this module in the playground first and switching over each npm dependency one at a time to see when it triggers?

Thanks very much for the investigation work so far, truly appreciated.

**Comment by silverbackdan** [comment] 2023-10-16 14:48
So it turns out this happens on a brand new module with this module installed. The reason the errors weren't showing on a brand new module was because in my `./playground/.env` I have `CONSOLA_LEVEL=4`

So it just is not outputting any errors unless verbose logging is on.

**Comment by ineshbose** [comment] 2023-10-16 21:20
You're quite right.. this is really great to catch - thank you very much. This exposes an issue now and it'll need to be investigated further.

**Comment by ineshbose** [comment] 2024-01-27 16:55
@silverbackdan, just came to check this issue - could you confirm if it persists in the latest versions of Nuxt and this module please? I tested it myself and seems to be resolved, but would like your confirmation on this.

**Comment by ineshbose** [comment] 2024-02-03 19:12
Let me know if you're getting warnings from your end on updating; I'll reopen.

**Closed** 2024-02-03 19:12 UTC
Labels: bug, pending
