### ISSUE TITLE
ERROR ExperimentalWarning: CommonJS module is loading ES Module

### ISSUE THREAD

**Issue by kswedberg** [nuxt-modules/tailwindcss#927] opened 2024-12-09 16:22 UTC
### Environment

- Operating System: Darwin
- Node Version:     v22.12.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      default
- Runtime Modules:  @pinia/nuxt@0.9.0, @nuxtjs/i18n@8.5.6, nuxt-security@2.1.5, nuxt-eslint-globals@2.1.4, nuxt-auth-utils@0.5.5
- Build Modules:    -

### Describe the bug

Using Node LTS version (`22.12.0`) produces this error/warning:

```
[4:24:26 PM]  ERROR  (node:94662) ExperimentalWarning: CommonJS module [...]/nuxt3-app/.nuxt/tailwind.config.cjs is loading ES Module [...]/nuxt3-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
```

Is there a way @nuxt/tailwindcss could produce an ES module instead (e.g. `.nuxt/tailwind.config.mjs`)?

### Logs

```shell-script

```

**Comment by ineshbose** [comment] 2024-12-09 16:33
Possible duplicate of https://github.com/nuxt-modules/tailwindcss/issues/902 - could you try nightly version and see if the issue persists?

**Comment by Baloche** [comment] 2024-12-11 09:50
I am also reproducing when using latest `nuxt` and `@nuxt/ui` dependencies. Using the nightly of `@nuxt/tailwindcss` does not remove the error 😢

**Comment by ineshbose** [comment] 2024-12-13 18:58
I guess I should go down this route again: #922

**Comment by skkap** [comment] 2024-12-14 05:55
Getting the same error with clean nuxt setup

```
    "@nuxtjs/tailwindcss": "^6.12.2",
    "nuxt": "^3.14.1592",
```

**Comment by davidreyg** [comment] 2024-12-16 15:41
I'm also running nuxt inside devcontainer. same issue. :(
this [npm](https://github.com/npm/cli/issues/7857) issue suggest upgrading node to v23.4.0. 
It didn't work for me.

**Comment by ineshbose** [comment] 2024-12-16 15:42
Working on a fix!

**Comment by polygxn** [comment] 2024-12-16 19:48
it does persist

**Comment by ineshbose** [comment] 2024-12-17 20:49
Ah, I guess issue will persist if any config file uses ESM syntax. Let me reopen and investigate on priority.

**Comment by mavyfaby** [comment] 2024-12-19 12:04
any updates on these? I can't run nuxt on my project until this fixed gets merged.

**Comment by ineshbose** [comment] 2024-12-19 12:06
> any updates on these? I can't run nuxt on my project until this fix gets merged.
> 

Could you try adding `tailwindcss.disableHMR: true` in your nuxt.config as a workaround?

**Comment by fmgrafikdesign** [comment] 2024-12-19 20:10
> Could you try adding `tailwindcss.disableHMR: true` in your nuxt.config as a workaround?

This did not resolve the issue for me. Still getting a `ERROR  [worker reload] [worker init] <snip>/.nuxt/dev/index.mjs failed`

**Comment by ineshbose** [comment] 2024-12-19 20:14
> > Could you try adding `tailwindcss.disableHMR: true` in your nuxt.config as a workaround?
> 
> This did not resolve the issue for me. Still getting a `ERROR  [worker reload] [worker init] <snip>/.nuxt/dev/index.mjs failed`

Hm, thats a dev server startup issue. Might not 100% be tailwind module issue. Could try the suggestion in this comment to see what exactly is the error? https://github.com/primefaces/primevue/issues/6712#issuecomment-2509671362

**Comment by fmgrafikdesign** [comment] 2024-12-19 20:38
Thank you for linking this! This allowed me to debug :) The issue was in fact that I was on a new device and had not set up the .env with secrets correctly because they are not checked into the repo. Seems like the nitropack error swallowed the actual reason, as per your linked comment. Thank you for taking your time to help me out 👍

**Comment by fmgrafikdesign** [comment] 2024-12-19 20:46
FWIW I came here because I too had the CommonJS module is loading ES Module error and thought it was the cause of the dev server startup error - upgrading to Node 23 fixed the warning, using `6.12.2` of the nuxt module

**Closed** 2024-12-25 18:02 UTC
Labels: bug

**Comment by ineshbose** [comment] 2024-12-25 18:03
Apologies for taking a while - I was quite puzzled with the Vite dev server issues in the environment and realised it was mostly due to `exposeConfig`, so we are now able to have a ESM config. Please try out [nightly version](https://tailwindcss.nuxtjs.org/getting-started/installation#nightly-releases) to confirm if the fix is working, and I'll make a stable release accoringly.

**Comment by arun-mani-j** [comment] 2024-12-25 18:52
Thanks a lot! Bugs during holidays are always annoying, but thanks for working on it. Merry Christmas!!

-------- Original Message --------

**Comment by s-slavchev** [comment] 2024-12-26 21:48
had the same error in the console and after trying the suggestions above here here is my feedback:

1. Using the nightly channel did not solve the issue for me _(node v22.12.0)_
2. Switching to node v23.5.0 solved the problem

**Comment by navinpeiris** [comment] 2024-12-27 01:48
Tested with the nightly release and can confirm that the warning no longer appears and everything works as expected. Thanks for getting this sorted during the holidays @ineshbose 🫶

Package versions:

```json
    "nuxt": "^3.15.0",
    "@nuxtjs/tailwindcss": "npm:@nuxtjs/tailwindcss@nightly",
```

**Comment by aquila1968** [comment] 2024-12-27 11:58
> Had the same error in the terminal and after trying the suggestions above here here is my feedback:
> 
> 1. Using the nightly channel did not solve the issue for me _(node v22.12.0)_
> 2. Switching to node v23.5.0 solved the problem

for me as well

**Comment by ineshbose** [comment] 2024-12-27 23:41
> Had the same error in the terminal and after trying the suggestions above here here is my feedback:
> 
> 1. Using the nightly channel did not solve the issue for me _(node v22.12.0)_
> 2. Switching to node v23.5.0 solved the problem

Hmm, would it be possible to get more context by [a reproduction](https://stackblitz.com/github/nuxt-modules/tailwindcss/tree/docs-examples/examples/basic-usage) please?

**Comment by Droidion** [comment] 2024-12-30 22:43
Using nightly on node 22.12 solves the problem.

**Comment by dungsil** [comment] 2024-12-31 05:44
In my case also I need to use nightly version and Node v23.5.0 so I don't see the error. It is still visible in v23.4.0.


`nuxt info`:
```
------------------------------
- Operating System: Windows_NT
- Node Version:     v23.5.0
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.7.4, @nuxtjs/color-mode@3.5.2, @nuxtjs/tailwindcss@6.13.0-20241225-182546-3a7a8a0, @vueuse/nuxt@12.2.0, radix-vue/nuxt
- Build Modules:    -
------------------------------
```

**Comment by gmdias727** [comment] 2024-12-31 22:48
For me adding the `"tailwindcss": "npm:@nuxtjs/tailwindcss@nightly",` into "devDependencies" didn't work

meanwhile adding `disableHMR: true,` into `nuxt.config.ts` as a workaround makes the warning stop.

**Comment by ineshbose** [comment] 2024-12-31 23:13
> For me adding the `"tailwindcss": "npm:@nuxtjs/tailwindcss@nightly",` into "devDependencies" didn't work

just want to confirm as its a common mistake at times, you are updating `@nuxtjs/tailwindcss` in your package.json, not `tailwindcss` right?

**Comment by jayjake0** [comment] 2025-01-03 10:32
node -v
v23.5.0

solved the issue.

**Comment by gmdias727** [comment] 2025-01-03 13:00
> > For me adding the `"tailwindcss": "npm:@nuxtjs/tailwindcss@nightly",` into "devDependencies" didn't work
> 
> just want to confirm as its a common mistake at times, you are updating `@nuxtjs/tailwindcss` in your package.json, not `tailwindcss` right?

my package.json:

```json
{
  "name": "potato",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix"
  },
  "dependencies": {
    "@mdi/font": "^7.4.47",
    "@nuxt/fonts": "^0.10.3",
    "@pinia/nuxt": "^0.9.0",
    "@vicons/ionicons5": "^0.13.0",
    "nuxt": "^3.14.1592",
    "nuxt-app": "file:",
    "pinia": "^2.3.0",
    "vue": "latest",
    "vue-router": "latest",
    "vuetify-nuxt-module": "^0.18.3",
    "vuetify-sonner": "^0.3.20"
  },
  "devDependencies": {
    "@nuxt/eslint": "^0.7.4",
    "@nuxtjs/tailwindcss": "^6.12.2",
    "@stylistic/eslint-plugin": "^2.12.1",
    "@types/tailwindcss": "^3.0.11",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.17.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.2.1",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.7.2",
    "unplugin-auto-import": "^0.19.0",
    "unplugin-vue-components": "^0.28.0",
    "vite-plugin-vuetify": "^2.0.4",
    "vuetify": "^3.7.6"
  }
}
```

I think I've installed tailwind with `npx nuxi@latest module add tailwindcss` only and as you can see `"tailwindcss": "^3.4.17"` is the only thing that exists inside package.json.

I'm still using disableHMR at nuxt.config.ts as a workaround btw

tailwindcss: {
    disableHMR: true,
}

And to answer your question I'm definetely updating `tailwindcss` package, I don't think I have any `@nuxtjs/tailwindcss`

**Comment by navinpeiris** [comment] 2025-01-03 13:10
Hi @gmdias727,

You're meant to point `@nuxtjs/tailwindcss`, the second item in your `devDependencies` to `npm:@nuxtjs/tailwindcss@nightly`, not `tailwindcss`.

See: https://github.com/nuxt-modules/tailwindcss/issues/927#issuecomment-2563226526

**Comment by forinda** [comment] 2025-01-08 08:06
Here is ahow to set it up

```diff
{
  "devDependencies": {
-   "@nuxtjs/tailwindcss": "^6.10.0"
+   "@nuxtjs/tailwindcss": "npm:@nuxtjs/tailwindcss@nightly"
  }
}
```
You can check the documentatioin here [ Link to resource](https://tailwindcss.nuxtjs.org/getting-started/installation#opting-into-the-nightly-channel)

**Comment by PavlosDefoort** [comment] 2025-01-09 18:57
### **My Experience and Current Solution**

I've also encountered this error recently. In my case, the error originates from both the `@nuxt/tailwindcss` and the `@nuxt/ui` packages. Since `@nuxt/ui` internally uses TailwindCSS, it suggests that the root cause might be related to the `@nuxt/tailwindcss` library.

#### **Steps I Tried**
1. **Using the Nightly Version**:  
   I initially tried switching to the nightly version in `devDependencies` while using Node.js 22. Unfortunately, this did not resolve the issue.

2. **Node.js Version Change**:  
   I found that the error could be resolved by either:
   - Downgrading to **Node.js 20**, or
   - Upgrading to **Node.js 23.5**.

   Since **Vercel deployment** does not currently support Node.js 23.5, I opted to use Node.js 20 as a temporary solution. This approach has been working well for me so far.

#### **Key Takeaways**
While I'm unsure if this is fundamentally a Node.js issue, trying a different Node.js version seems to be a feasible workaround. I recommend experimenting with compatible versions to see if it resolves the problem for your setup.

#### **My Working Solution**
Here is my `package.json` for reference (note that I've reverted to the stable version instead of the nightly version):

```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxt/ui": "^2.20.0",
    "@nuxtjs/google-fonts": "^3.2.0",
    "@nuxtjs/tailwindcss": "^6.12.2",
    "axios": "^1.7.7",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "lucide-vue-next": "^0.469.0",
    "nuxt": "^3.15.0",
    "pixi.js": "^8.6.6",
    "radix-vue": "^1.9.11",
    "tech-stack-icons": "^2.1.0",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@iconify-json/radix-icons": "^1.2.0",
    "typescript": "^5.7.2"
  }
}
```

---

I hope this helps others experiencing a similar issue. Let me know if additional context would be useful!

**Comment by hidarikani** [comment] 2025-01-11 20:08
I'm not using `nuxt`, but I did get similar error. I made it disappear by renaming `vite.config.ts` to `vite.config.mts` not sure if it's good or bad but it worked.

**Comment by ineshbose** [comment] 2025-01-11 20:49
> I'm not using `nuxt`, but I did get similar error. I made it disappear by renaming `vite.config.ts` to `vite.config.mts` not sure if it's good or bad but it worked.

I think that wouldn't be encouraged (as vite config should be inlined within nuxt.config).

I do want to point out that I would not expect or ask devs to be switching node versions (esp to non-LTS) just to make this go away. A stable release is on its way, but if issues persist, I would believe them to be per-project basis, and I am happy to debug if context/repro would be provided.
