### ISSUE TITLE
 ERROR  Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addServerImports'

### ISSUE THREAD

**Issue by Foddie2** [nuxt-modules/tailwindcss#783] opened 2023-12-26 17:06 UTC
ERROR  Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addServerImports'     

```
  import { createResolver, extendViteConfig, defineNuxtModule, addServerHandler, addTemplate, addComponent, addImports, addServerImports, addComponentsDir } from '@nuxt/kit';
  ^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addServerImports'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

```

**Comment by ineshbose** [comment] 2023-12-26 17:12
What versions of Nuxt and this module are you on? Can you provide a reproduction? I feel you may be opening a duplicate of https://github.com/nuxt-modules/tailwindcss/issues/778 again.

**Comment by Foddie2** [comment] 2023-12-26 18:24
Nuxt project info:                                                                                                       

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.0
- CLI Version:      3.10.0
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, devtools, css, plugins, devServerHandlers, postcss, modules, content, runtimeConfig
- Runtime Modules:  @nuxt/content@2.10.0, nuxt-purgecss@2.0.0, @nuxtjs/pwa@3.3.5, @vite-pwa/nuxt@0.3.6, @nuxt/postcss8@1.1.3, nuxt-mailer@0.11.0, @nuxtjs/tailwindcss
- Build Modules:    -

**Comment by ineshbose** [comment] 2023-12-26 18:26
You have omitted the version of the module. Please share your package.json

**Comment by Foddie2** [comment] 2023-12-26 18:27
{
  "name": "techbytes-today",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^5.0.0",
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@latest",
    "@nuxt/content": "^2.9.0",
    "@nuxt/devtools": "^0.8.2",
    "@nuxt/image": "^1.0.0-rc.3",
    "@nuxtjs/google-fonts": "^3.0.2",
    "@nuxtjs/pwa": "^3.3.5",
    "@tailwindcss/typography": "^0.5.10",
    "@types/node": "^18.17.1",
    "@vite-pwa/nuxt": "^0.3.2",
    "autoprefixer": "^10.4.14",
    "nuxt": "^3.8.2",
    "nuxt-purgecss": "^2.0.0",
    "nuxt-vite": "^0.3.5",
    "postcss": "^8.4.27",
    "sass": "^1.65.1",
    "tailwindcss": "^3.3.3"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "aos": "^2.3.4",
    "flowbite": "^1.8.1",
    "node-fetch": "^3.3.2",
    "node-fetch-commonjs": "^3.3.2",
    "nodemailer": "^6.9.7",
    "nuxt-jsonld": "^2.0.8",
    "nuxt-mail": "^4.0.1",
    "nuxt-mailer": "^0.11.0",
    "nuxt-newsletter": "^0.2.0",
    "vue": "^3.3.11",
    "vue-router": "^4.2.5",
    "yarn": "^1.22.19"
  },
  "resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
  },
  "type": "module"
}

**Comment by ineshbose** [comment] 2023-12-26 18:30
I don't see `@nuxtjs/tailwindcss` on there, and you have `@nuxt/kit@3.0.0-rc.13` which I have pointed out has had breaking changes until stable `^3.0.0`. Why are you on RC version?

**Closed by ineshbose** 2023-12-26 18:30 UTC

**Comment by ineshbose** [comment] 2023-12-26 18:37
If you need to continue using RC version of `@nuxt/kit`, you can look into using `v6.1.3` or earlier version of this module, but I still can't guarantee compatibility. Please be mindful of opening duplicate issues on this repository.
