### ISSUE TITLE
config from tailwinds.config not applied in the app !!

### ISSUE THREAD

**Issue by peter-emad99** [nuxt-modules/tailwindcss#769] opened 2023-11-25 20:59 UTC
I'm using this module embeded with nuxt-ui ...for some reason that i don't know when i put custom tailwind config ..in tailwind.config.ts
it doesn't apply in any component...but when i put the same config in the config option of the module option in nuxt.config ..it works 

i want to use the tailwind.config ..so the tailwind interllisense extension ..read the custom config 
any thought what i'm doing wrong ??

**Comment by ineshbose** [comment] 2023-11-25 21:04
Sorry, I'm not quite sure what you mean. Can you provide a replication/video to elaborate what you're talking about?

For editor support, we have - https://tailwindcss.nuxtjs.org/tailwind/editor-support.

**Comment by peter-emad99** [comment] 2023-11-25 21:41
i think i put my finger on the problem here ....
every thing work if I restart the dev server ..despite the server is restarting automatically when i make changes in tailwind config file !!! but nothing reflect in browser unless i stop the process and run it again ..
any idea why ??

**Comment by ineshbose** [comment] 2023-11-25 21:42
Please provide a minimal reproduction of your issue over Stackblitz - https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz - and we can investigate it properly.

**Comment by madebyfabian** [comment] 2023-11-26 18:46
Hi there, I have the same issue for a while now. 

## Reproduction
1. Open the StackBlitz: https://stackblitz.com/edit/github-mrbfhk
2. Install deps and run the devserver
3. Change a value in the `tailwind.config.ts` file 
    -> for example the custom theme color `theme.extend.colors.accent.DEFAULT` from `green` to `red`
4. The devserver restarts, attempting to apply the changes. It does start without any errors, but (in this example) the color value in the generated css file is not being updated, still displayed as `green`. 
5. To apply those changes, you must quit the devserver and restart it manually.

**Comment by ineshbose** [comment] 2023-11-26 18:57
Thanks for the repro @madebyfabian.

It clears up that this isn't related to `nuxt/ui`. Do you think #682 is possibly related to this?

**Comment by madebyfabian** [comment] 2023-11-27 06:09
@ineshbose Ah, just finding this issue. Yeah, I think this describes the same. And yeah, happens on nuxt/tailwind, not nuxt/ui. I think this issue can then be closed as a duplicate of #682

**Closed** 2023-11-27 06:41 UTC
Labels: question
