### ISSUE TITLE
Duplicate CSS classes created

### ISSUE THREAD

**Issue by ciaran-io** [nuxt-modules/tailwindcss#531] opened 2022-09-10 19:21 UTC
### Version
@nuxtjs/tailwindcss: 5.3.3
nuxt: 3.0.0-rc.9

### Reproduction Link
https://631cddb4b9acb87d305ae359--fantastic-quokka-8abacb.netlify.app

### Repo
gh repo clone ciaran-io/sandbox
[nuxt3@rc9]

### Steps to reproduce
Base setup for Nuxt 3 & Tailwindcss module.

### What is Expected?
Expected CSS style to be created in one css file.

### What is actually happening?
Duplicated css:

When adding styles in the style tag the same styles are added to the main css file via Tailwind as well as a separate css.vue file.

Vue template
-----------

![code](https://user-images.githubusercontent.com/58338331/189498239-0baa64f7-a67e-437f-8417-23aa8f632ab7.png)

Css from Vue template
----
<img width="1405" alt="code-index vue" src="https://user-images.githubusercontent.com/58338331/189498432-0ddc9b4a-278a-4637-aba1-94c037b25c0a.png">

Css from tailwind created global file
---
<img width="791" alt="code-main css" src="https://user-images.githubusercontent.com/58338331/189498456-30a2ff56-c793-45bf-aa21-5373eda574ba.png">

**Comment by d4g0** [comment] 2022-10-12 03:53
## This happens also with a fresh install.

I have at the moment a cero css styles, or tw classes,  a bare html project.
Im using: 
```json
 "devDependencies": {
    "@nuxtjs/tailwindcss": "^5.3.5",
    "@supabase/supabase-js": "^2.0.0",
    "nuxt": "3.0.0-rc.11",
    "tailwindcss": "^3.1.8",
  }
```
And is shipping production with the duplication too, tawilwind css shiped twice, as a head style tag, and as a prefetch stylesheet.

## DOM:
![Screenshot from 2022-10-11 23-44-37](https://user-images.githubusercontent.com/34744883/195245357-c5cae85f-2c1e-4317-a163-87d9cd3b837f.png)

## Network:
![Screenshot from 2022-10-11 23-44-28](https://user-images.githubusercontent.com/34744883/195245365-05cd4fb7-98c0-4698-8b07-fb8a1ea90c3d.png)

**Comment by d4g0** [comment] 2022-10-12 04:18
The same behavior happens even when TailwinCSS is installed with out this module, i just set up 
```ts
//nuxt.config.ts
css:[
        '~/assets/css/main.css'
    ],
    postcss: {
        config: true,
        plugins: {
            tailwindcss: {},
        },
    },
```

```css
/* main.css */
@tailwind base;
@tailwind utilities;
@tailwind components;
```

**Comment by memic84** [comment] 2022-10-13 12:28
Same here, default setup for my project.

The external css file is inlined in the <head>, and all styles are applied twice.

**Comment by memic84** [comment] 2022-10-13 12:34
It's a new feature in RC.10 where Critical styles are inlined, it seems that the condition to inline is when the styles are in a layout, where in my case it's about header and footer styles.

I've been able to turn it off with: `experimental: { inlineSSRStyles: false }` in `nuxt.config.js`

https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.10

**Comment by hecktarzuli** [comment] 2023-04-19 16:43
inlineSSRStyles didn't do anything to me, so I had to work around it.
https://twitter.com/JoshDeltener/status/1648718573236305921

**Comment by LouisMazel** [comment] 2023-05-10 00:38
Same issue for me in multiple projects with Nuxt 3. 

I tried without success to make a reproduction but the module doesn't work with stackblitz: https://stackblitz.com/edit/nuxt-tailwind?file=nuxt.config.ts

**Comment by MikeLee0358** [comment] 2023-05-14 22:09
It happens to vanilla CSS, in dev server will be ok, but in the production. will be like this image
<img width="304" alt="截圖 2023-05-15 上午6 06 15" src="https://github.com/nuxt-modules/tailwindcss/assets/108295892/a5ce26e4-111f-4fd9-a7be-c7a78434a0f8">

simple demo: [https://mikelee-qrcode.netlify.app/]

**Comment by brokuka** [comment] 2023-08-14 09:22
any update?

**Comment by jrutila** [comment] 2023-10-23 04:58
I got it working after reading this (https://tailwindcss.nuxtjs.org/getting-started/setup).

I removed the `css` setting from `nuxt.config.ts` and moved my main.css to `/assets/css/tailwind.css`.

**Comment by FBLudwig** [comment] 2023-11-18 15:26
I'm using SSR and have a `/assets/css/main.scss` file where I use the @tailwind and @layer directives.
It seems like the default Tailwind styles are inlined in addition to the Tailwind styles generated from my `/assets/css/main.scss`.

I did a similar workaround and created an empty `/assets/css.tailwind.css` which solved the issue for me.

**Comment by Red-Asuka** [comment] 2024-01-05 07:09
I have the same issue. The document mentions that it will automatically detect the following path: `./assets/css/tailwind.css`. If it doesn't exist, it will use the default CSS file. However, my project uses SCSS and I have manually imported it in nuxt.config.ts. This leads to duplicate imports of classes. Can you provide an option to disable the automatic generation feature or specify the path for the CSS file?

**Comment by ineshbose** [comment] 2024-01-19 09:19
> Can you provide an option to disable the automatic generation feature or specify the path for the CSS file?

You can set `cssPath: false`

**Comment by samuelreichor** [comment] 2024-01-24 09:54
Is there a quick way for you to change the defaults in `module.ts`  so that the `cssPath` is customizable via the nuxt config? I would like to use a pcss file for my css entry point because I need to import other pcss files in that file. So tailwind.css won't work for me. 

```javascript
const defaults = (nuxt = useNuxt()): ModuleOptions => ({
  configPath: 'tailwind.config',
  cssPath: join(nuxt.options.dir.assets, 'css/tailwind.css'),
  config: defaultTailwindConfig,
  viewer: true,
  exposeConfig: false,
  disableHmrHotfix: false,
  quiet: nuxt.options.logLevel === 'silent',
  editorSupport: false,
})
```

**Comment by ineshbose** [comment] 2024-01-24 09:56
> Is there a quick way for you to change the defaults in `module.ts` so that the `cssPath` is customizable via the nuxt config? I would like to use a pcss file for my css entry point because I need to import other pcss files in that file. So tailwind.css won't work for me.
> 
> ```js
> const defaults = (nuxt = useNuxt()): ModuleOptions => ({
>   configPath: 'tailwind.config',
>   cssPath: join(nuxt.options.dir.assets, 'css/tailwind.css'),
>   config: defaultTailwindConfig,
>   viewer: true,
>   exposeConfig: false,
>   disableHmrHotfix: false,
>   quiet: nuxt.options.logLevel === 'silent',
>   editorSupport: false,
> })
> ```

You can do this in your `nuxt.config`:

```ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss'],
  tailwindcss: { cssPath: '~/assets/css/main.pcss' }
})
```

**Comment by ineshbose** [comment] 2024-01-24 10:38
Does this issue persist? I believe now this is more of handling `cssPath` (module does it for you, and you need not add it to `nuxt.options.css`); critical styles however is more Nuxt functionality so for that you can refer https://github.com/nuxt-modules/tailwindcss/issues/531#issuecomment-1277539649. I'll close this for now, but happy to reopen if important (would also really appreciate Stackblitz replication).

**Closed by ineshbose** 2024-01-24 10:38 UTC
Labels: bug
